### ISSUE TITLE
Print Document Reference and Reference Chunk to ODS

### ISSUE THREAD

**Issue by samiulhq** [samiulhq/LLM-RAG-SAS#1]
In the existing implementation, the Result of the similarity search is not printed to the ODS. Printing this information will help the end user better understand and validate the results generated by LLM.

**Comment by SundareshSankaran** [comment]
Similar documents can get quite bulky.  We might like to think about redirecting to output tables.

**Comment by SundareshSankaran** [comment]
Similarity Search results are now redirected to an output table.  for ease of use, the same output table functions as the store of the LLM and the search results.  This is deliberate and will also facilitate evaluation of results from a relevance perspective.
